routes/routes.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, send_file
from models.models import Eo_DB, LogsDB, Eo_data_conflicts, Eo_candidatesDB
from extensions import extensions
import os
from functions import read_sap_eo_xlsx_file, read_be_eo_xlsx_file_v2, read_be_eo_xlsx_file_v3, generate_excel_master_eo, generate_excel_conflicts, generate_excel_add_candidates, generate_excel_calendar_status_eo, generate_excel_model_eo, read_eo_models_xlsx_file, read_delete_eo_xlsx_file, read_update_eo_data_xlsx_file, generate_eo_diagram_data, eo_data_calculation


UPLOAD_FOLDER = '/uploads'

db = extensions.db

# home = Blueprint('home', __name__, template_folder='templates')
home = Blueprint('home', __name__)

@home.route('/')
def home_view():
  eo_data=Eo_DB.query.order_by(Eo_DB.teh_mesto, Eo_DB.be_code).all()
  log_data = LogsDB.query.filter_by(log_status = "new").all()
  conflicts_data = Eo_data_conflicts.query.filter_by(eo_conflict_status="active").all()
  number_of_active_conflicts = len(list(conflicts_data))
  add_candidates_data = Eo_candidatesDB.query.all()
  number_of_add_candidates = len(list(add_candidates_data))

  # eo_data.sort_values(['teh_mesto', 'be_description', 'eo_class_code', 'head_eo_model_descr'], inplace=True)
  return render_template('home.html', eo_data = eo_data, log_data=log_data, number_of_active_conflicts=number_of_active_conflicts, number_of_add_candidates=number_of_add_candidates)



@home.route('/eo_data_calc', methods=['GET', 'POST'])
def eo_data_calc():
  if request.method == 'POST': 
    
    eo_data_calculation.eo_data_calculation()
    message = "Данные пересчитаны"
    

    flash(message, 'alert-success')
    return redirect(url_for('home.home_view'))
    
  redirect(url_for('home.home_view'))


def allowed_file(filename):
  ALLOWED_EXTENSIONS = {'xlsx','csv'}  
  return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@home.route('/upload_delete_eo_file', methods=['GET', 'POST'])
def upload_delete_eo_file():
  if request.method == 'POST':
    uploaded_file = request.files['file']
    if uploaded_file.filename == '':
      message = f"файл с пустым именем"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))
    
    elif allowed_file(uploaded_file.filename) == False:
      message = f"Неразрешенное расширение файла {uploaded_file.filename}"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))

    elif "delete_eo" not in uploaded_file.filename:
      message = "В имени файла нет текста delete_eo"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    elif "xlsx" not in uploaded_file.filename.lower():
      message = "В имени файла нет расширения xlsx"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    else:    
      uploaded_file.save(os.path.join('uploads', "delete_eo.xlsx"))
      message = f"файл {uploaded_file.filename} загружен"
      # read_be_eo_xlsx_file.read_be_eo_xlsx()
      read_delete_eo_xlsx_file.read_delete_eo_xlsx()
      flash(message, 'alert-success')
      return redirect(url_for('home.home_view'))

    return 'not uploaded'



@home.route('/update_eo_data_file', methods=['GET', 'POST'])
def update_eo_data_file():
  if request.method == 'POST':
    uploaded_file = request.files['file']
    if uploaded_file.filename == '':
      message = f"файл с пустым именем"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))
    
    elif allowed_file(uploaded_file.filename) == False:
      message = f"Неразрешенное расширение файла {uploaded_file.filename}"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))

    elif "update_eo_data" not in uploaded_file.filename:
      message = "В имени файла нет текста update_eo_data"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    elif "xlsx" not in uploaded_file.filename.lower():
      message = "В имени файла нет расширения xlsx"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    else:    
      uploaded_file.save(os.path.join('uploads', "update_eo_data.xlsx"))
      message = f"файл {uploaded_file.filename} загружен"
      # read_be_eo_xlsx_file.read_be_eo_xlsx()
      read_update_eo_data_xlsx_file.read_update_eo_data_xlsx()
      flash(message, 'alert-success')
      return redirect(url_for('home.home_view'))

    return 'not uploaded'




@home.route('/upload_models_eo_file', methods=['GET', 'POST'])
def upload_models_eo_file():
  if request.method == 'POST':
    uploaded_file = request.files['file']
    if uploaded_file.filename == '':
      message = f"файл с пустым именем"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))
    
    elif allowed_file(uploaded_file.filename) == False:
      message = f"Неразрешенное расширение файла {uploaded_file.filename}"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))

    elif "model_eo" not in uploaded_file.filename:
      message = "В имени файла нет текста model_eo"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    elif "xlsx" not in uploaded_file.filename.lower():
      message = "В имени файла нет расширения xlsx"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    else:    
      uploaded_file.save(os.path.join('uploads', "eo_models.xlsx"))
      message = f"файл {uploaded_file.filename} загружен"
      # read_be_eo_xlsx_file.read_be_eo_xlsx()
      read_eo_models_xlsx_file.read_eo_models_xlsx()
      flash(message, 'alert-success')
      return redirect(url_for('home.home_view'))

    return 'not uploaded'


@home.route('/upload_be_eo_file', methods=['GET', 'POST'])
def upload_be_eo_file():
  if request.method == 'POST':
    uploaded_file = request.files['file']
    if uploaded_file.filename == '':
      message = f"файл с пустым именем"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))
    
    elif allowed_file(uploaded_file.filename) == False:
      message = f"Неразрешенное расширение файла {uploaded_file.filename}"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))

    elif "be_eo_data" not in uploaded_file.filename:
      message = "В имени файла нет текста be_eo_data"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    elif "xlsx" not in uploaded_file.filename:
      message = "В имени файла нет расширения xlsx"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))

    else:    
      uploaded_file.save(os.path.join('uploads', "be_eo_data.xlsx"))
      message = f"файл {uploaded_file.filename} загружен"
      # print(f"файл {uploaded_file.filename} загружен")
      # read_be_eo_xlsx_file.read_be_eo_xlsx()
      read_be_eo_xlsx_file_v3.read_be_eo_xlsx()
      flash(message, 'alert-success')
      return redirect(url_for('home.home_view'))

      
    return 'not uploaded'

@home.route('/upload_sap_eo_file', methods=['GET', 'POST'])
def upload_sap_eo_file():
  if request.method == 'POST':
    # check if the post request has the file part
  
    uploaded_file = request.files['file']
    if uploaded_file.filename == '':
      message = f"файл с пустым именем"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))
    elif allowed_file(uploaded_file.filename) == False:
      message = f"Неразрешенное расширение файла {uploaded_file.filename}"
      flash(message, 'alert-danger')
      return redirect(url_for('home.home_view'))
    elif "sap_eo_data" not in uploaded_file.filename:
      message = "В имени файла нет текста sap_eo_data"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))
    elif "xlsx" not in uploaded_file.filename:
      message = "В имени файла нет расширения xlsx"
      flash(message, 'alert-danger')    
      return redirect(url_for('home.home_view'))
    else:    
      # uploaded_file.save(os.path.join('uploads', uploaded_file.filename))
      uploaded_file.save(os.path.join('uploads', "sap_eo_data.xlsx"))
      message = f"файл {uploaded_file.filename} загружен"
      read_sap_eo_xlsx_file.read_sap_eo_xlsx()
      flash(message, 'alert-success')
    return redirect(url_for('home.home_view'))
  
  return 'not uploaded'




@home.route('/download_delete_eo', methods=['GET', 'POST'])
def download_delete_eo():
  if request.method == 'POST': 
    return send_file("downloads/delete_eo.xlsx", as_attachment=True) 
  return 'not downloaded delete_eo'



@home.route('/download_update_eo_data', methods=['GET', 'POST'])
def download_update_eo_data():
  if request.method == 'POST': 
    return send_file("downloads/update_eo_data.xlsx", as_attachment=True) 
  return 'not downloaded update_eo_data'

@home.route('/download_models_eo', methods=['GET', 'POST'])
def download_models_eo():
  if request.method == 'POST': 
    generate_excel_model_eo.sql_to_model_eo()
    return send_file("downloads/model_eo.xlsx", as_attachment=True) 
  return 'not downloaded be_eo_data_template'



@home.route('/download_calendar_eo_v2_file', methods=['GET', 'POST'])
def download_calendar_eo_v2_file():
  if request.method == 'POST': 
    generate_eo_diagram_data.generate_eo_diagram_data()
    return send_file("downloads/eo_calendar_data_v2.xlsx", as_attachment=True) 
  return 'not downloaded be_eo_data_template'

@home.route('/download_calendar_eo_file', methods=['GET', 'POST'])
def download_calendar_eo_file():
  if request.method == 'POST': 
    generate_excel_calendar_status_eo.sql_to_eo_calendar_master()
    return send_file("downloads/calendar_eo.xlsx", as_attachment=True) 
  return 'not downloaded be_eo_data_template'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">

  
{% endblock %}
<title>{% block title %}  {% endblock %}</title>
</head>
<body>
  
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes style="list-style: none;">
    
      {% for category, message in messages %}
      <div class="alert {{ category }} alert-dismissible fade show" role="alert">  
      <li>{{ message }}</li>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
    <div id="content">
        {% block content %}
        {% endblock %}
    </div> <!-- Это конец блока Content-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>

<script>
  $('.alert').alert()
</script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block head %}

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap4.min.css">

{% endblock %}

{% block content %}

<div class="container" style="margin-top: 10px">
        <div class="row">
          <div class='col'>
      
            
            {#<a href="{{url_for( 'home.upload_file' )}}"><button type="button" class="btn btn-secondary">Upload</button></a>#}
          </div>
        </div>
  
        <div class="row">
              <div class="col text-center d-flex justify-content-center">
                  <h4>SAP master EO data check</h4>
              </div>
        </div>

  
        <div class="row">
              <div class="col d-flex justify-content-start">
                  <div>
                      <form action = "{{url_for( 'home.conflicts' )}}" method=post enctype=multipart/form-data>
                        Конфликты ({{number_of_active_conflicts }})
                        <button class="btn btn-info" type="submit">Выгрузить</button>
                      </form>
                  </div>
                  <div style="margin-left: 20px; margin-bottom: 22px;">
                    <form action = "{{url_for( 'home.clean_conflicts' )}}" method=post enctype=multipart/form-data>

                        <button class="btn btn-info" type="submit">Очистить</button>
                      </form>
                  </div>

                  <div style="margin-left: 30px">
                      <form action = "{{url_for( 'home.add_candidates' )}}" method=post enctype=multipart/form-data>
                        Кандидаты на добавление ({{number_of_add_candidates}})
                        <button class="btn btn-info" type="submit">Выгрузить</button>
                      </form>
                  </div>
                  <div style="margin-left: 20px">
                    <form action = "{{url_for( 'home.clean_candidates' )}}" method=post enctype=multipart/form-data>
                
                        <button class="btn btn-info" type="submit">Очистить</button>
                      </form>
                  </div>

                  <div style="margin-left: 30px">
                      <form action = "{{url_for( 'home.eo_data_calc' )}}" method=post enctype=multipart/form-data>
                        Master_eo_data_recalculation
                        <button class="btn btn-info" type="submit">Расчет</button>
                      </form>
                  </div>
                  
                
              </div>
        </div>
  
        <div class="row">
              <div class="col text-center d-flex justify-content-center">
                   
                  <div> <!--див таблицы -->
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                      <thead>
                          <tr>
                              <th>Description</th>
                              <th>Upload</th>
                              <th>Download</th>
                          </tr>
                      </thead>
                      <tbody>
                        <tr>  
                          <td>Данные БДО САП</td>
                          <td>
                            <p>Загрузка данных БДО САП. Имя файла: <strong>"sap_eo_data.xlsx"</strong></p>
                            <form action = "{{url_for( 'home.upload_sap_eo_file' )}}" method=post enctype=multipart/form-data>
                            <input type=file name=file>
                            <button class="btn btn-primary" type="submit">Загрузить</button>
                          </form>
                          </td>
                          <td>
                        
                            <form action = "{{url_for( 'home.download_master_eo_file' )}}" method=post enctype=multipart/form-data>
                              Выгрузка мастер-данных БДО
                            <button class="btn btn-info" type="submit">Выгрузить</button>
                          </form>
                          </td>    
                        </tr>
                        <tr>
                          <tr>  
                          <td>Update Master eo_data</td>
                          <td>
                            <p>Загрузка обновления мастер-данных. Имя файла: <strong>"update_eo_data.xlsx"</strong></p>
                            <form action = "{{url_for( 'home.update_eo_data_file' )}}" method=post enctype=multipart/form-data>
                            <input type=file name=file>
                            <button class="btn btn-primary" type="submit">Загрузить</button>
                          </form>
                          </td>
                          <td>
                        
                            <form action = "{{url_for( 'home.download_update_eo_data' )}}" method=post enctype=multipart/form-data>
                              Шаблон загрузки update_eo_data
                            <button class="btn btn-info" type="submit">Выгрузить</button>
                          </form>
                          </td>    
                        </tr>
                        <tr>


                          
                          <td>
                            Данные из Бизнес-единиц
                          </td>
                          <td>
                            <p>Загрузка данных из файлов "Парк оборудования". Имя файла: <strong>"be_eo_data.xlsx"</strong>. Имя листа: <strong>"be_eo_data"</strong> </p>
                            
                            <form action = "{{url_for( 'home.upload_be_eo_file' )}}" method=post enctype=multipart/form-data>
                            <input type=file name=file>
                            <button class="btn btn-primary" type="submit">Загрузить</button>
                          </form>
                          </td>
                          <td>
                            <form action = "{{url_for( 'home.download_be_data_template' )}}" method=post enctype=multipart/form-data>
                              Шаблон загрузки данных из Бизнес единиц
                            <button class="btn btn-info" type="submit">Выгрузить</button>
                          </form>
                            
                          </td>
                        </tr>
                        <tr>
                          <td>
                            Календарный план ЕО
                          </td>
                          <td>
                            
                          </td>
                          <td>
                            <form action = "{{url_for( 'home.download_calendar_eo_file' )}}" method=post enctype=multipart/form-data>
                              Выгрузка календарного плана ЕО
                            <button class="btn btn-info" type="submit">Выгрузить</button>
                          </form>
                    
                          </td>
                        </tr>

                        <tr>
                          <td>
                            БДО Календарный план. v2
                          </td>
                          <td>
                            
                          </td>
                          <td>
                            <form action = "{{url_for( 'home.download_calendar_eo_v2_file' )}}" method=post enctype=multipart/form-data>
                              БДО Календарный план. v2
                            <button class="btn btn-info" type="submit">Выгрузить</button>
                          </form>
                    
                          </td>
                        </tr>

  
                        
                        <tr>
                          <td>
                            Модели ЕО
                          </td>
                          <td>
                            <p>Загрузка "Модели ЕО". Имя файла: <strong>"model_eo.xlsx"</strong>.</p>
                            
                            <form action = "{{url_for( 'home.upload_models_eo_file' )}}" method=post enctype=multipart/form-data>
                            <input type=file name=file>
                            <button class="btn btn-primary" type="submit">Загрузить</button>
                          </form>
                            
                          </td>
                          <td>
                            <form action = "{{url_for( 'home.download_models_eo' )}}" method=post enctype=multipart/form-data>
                              Выгрузка моделей ЕО
                            <button class="btn btn-info" type="submit">Выгрузить</button>
                          </form>
                    
                          </td>
                        </tr>
                         <tr>
                          <td>
                            Удаление записей из мастер-данных
                          </td>
                          <td>
                            <p>Загрузка "ЕО на удаление". Имя файла: <strong>"delete_eo.xlsx"</strong>. Имя листа: <strong>"delete_eo"</strong></p>
                            
                            <form action = "{{url_for( 'home.upload_delete_eo_file' )}}" method=post enctype=multipart/form-data>
                            <input type=file name=file>
                            <button class="btn btn-primary" type="submit">Загрузить</button>
                          </form>
                            
                          </td>
                          <td>
                            <form action = "{{url_for( 'home.download_delete_eo' )}}" method=post enctype=multipart/form-data>
                              Выгрузка шаблона на удаление записей
                            <button class="btn btn-info" type="submit">Выгрузить</button>
                          </form>
                    
                          </td>
                        </tr>
                          
                    </table>
                  </div> <!--конец дива таблицы -->
            </div>
        </div>    
                  
      <div class="row">
              <div class="col d-flex justify-content-center">
                  <h3>Logs</h3>
              </div>
      </div>
  
      <div class="row">
              <div class="col">
                  <!-- Блок с логами -->
                  <div class="text-left">
                    <ul class="list-group list-group-flush">
                      {% for log_record in log_data %}
                        <li class="list-group-item">{{log_record.log_date}} {{log_record.log_text}}</li>
                      {% endfor %}
                    </ul>
                  </div>
                  
              </div>
      </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap4.min.js"></script>  
  
  <script>
    $(document).ready(function () {
      $('#example').DataTable();
    });
</script>
{% endblock %}